"""create payments and outbox tables

Revision ID: 100e962cd18c
Revises:
Create Date: 2026-03-28 12:39:42.892853

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '100e962cd18c'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'payments',
        sa.Column('id_', sa.UUID(), nullable=False),
        sa.Column('idempotency_key', sa.String(length=255), nullable=False),
        sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column('currency', sa.Enum('RUB', 'USD', 'EUR', name='currency_enum'), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('metadata_', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column(
            'status',
            sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', name='payment_status_enum'),
            nullable=False,
        ),
        sa.Column('webhook_url', sa.String(length=2048), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id_'),
    )
    op.create_index(
        op.f('ix_payments_idempotency_key'), 'payments', ['idempotency_key'], unique=True
    )
    op.create_table(
        'outbox',
        sa.Column('id_', sa.UUID(), nullable=False),
        sa.Column('payment_id', sa.UUID(), nullable=False),
        sa.Column('event_type', sa.String(length=100), nullable=False),
        sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column(
            'status',
            sa.Enum('PENDING', 'PROCESSED', 'FAILED', name='outbox_status_enum'),
            nullable=False,
        ),
        sa.Column('attempts', sa.Integer(), nullable=False),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ['payment_id'],
            ['payments.id_'],
        ),
        sa.PrimaryKeyConstraint('id_'),
    )
    op.create_index(op.f('ix_outbox_payment_id'), 'outbox', ['payment_id'], unique=False)
    op.create_index('ix_outbox_status', 'outbox', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_outbox_status', table_name='outbox')
    op.drop_index(op.f('ix_outbox_payment_id'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_payments_idempotency_key'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
